version: "3"
   
services:
  db:
    image: postgres
    hostname: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=bd_student
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
    networks:
      - mynetwork
  web:
    build:
      context: .
    ports:
      - "8082:8082"
    networks:
      - mynetwork
    volumes:
      - .:/ui
    command: python manage.py runserver 0.0.0.0:8082
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:admin@db:5432/bd_student

volumes:
  pgdb:
networks:
  mynetwork: