# Generated by Django 4.1.7 on 2023-03-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nembers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlevel',
            name='total_student',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classlevel',
            name='level',
            field=models.CharField(max_length=100),
        ),
    ]
