# Generated by Django 4.1.6 on 2023-03-10 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nembers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name_plural': 'Admin'},
        ),
    ]
